---
output:
  pdf_document:
    pandoc_args: './paper_info.yaml'
    citation_package: natbib
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
  word_document:
    pandoc_args: './paper_info.yaml'
    reference_docx: ./resources/aog_word_style.docx
  html_document:
    pandoc_args: './paper_info.yaml'
fontfamily: mathpazo
fontsize: 11pt
anonymous: false
endnotes: false
bibliography: ../project.bib
biblio-style: ./resources/ajs.bst
---

```{r setup, echo=FALSE, warning=FALSE, error=FALSE, include=FALSE}
# If you want to do things in one R Markdown document then use the 
# chunk option eval to toggle between running with and without 
# compiling R code chunks
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, warning = FALSE, 
                      eval = TRUE)
#load data
#load libraries
```

# Introduction

Healthcare in the United States, while not restricted in variety, poses several barriers for individual access to its services. Private healthcare insurance provides the socially desired increase in choice of options, but often results in higher out of pocket costs and deductibles (Doonan et al. 2015). As a result, only the wealthy few with little to no health issues benefit. Medicare additionally provides significant choice, “but also entails significant out-of-pocket costs for its seniors and disabled beneficiaries” (Doonan et al. 2015, 755). Medicaid promises to give recipients open choice to providers, but the federal government allows states to secure waivers to instead provide a limited network (Doonan et al. 2015). Widespread use of Multiplan networks adds another node of complication to understanding access and coverage. This apparent limitless quantity of options has not, however, resulted in an increase in the quality of care recipients receive. As of 2011, “just under one-quarter of the inhabitants of the more developed regions lived in rural areas,” and while urban centers are generally assumed to be “less-healthy due to higher levels of overcrowding, air pollution, and stress,” they are in fact more healthy than their rural counterparts (Hughes 2019). Rural communities, specifically rural Indigenous communities in the United States, have unprecedented health disparities and limited regularity of healthcare (Kruse et al. 2016). 

In this study, I aim to measure the association between race and access to healthcare, which will be quantified in health insurance coverage. Specifically, I am asking to what extent do Indigenous populations in the United States have access to healthcare, and how is this correlated with urban versus rural status and class? Recent studies have criticized the overall biomedical approach of healthcare in the United States that has “developed over the last two centuries from heteropatriarchal assumptions of women as reproducers,” but few have solely focused on Indigenous communities in the United States and analyzed urban versus rural status as a higher level effect (Gurr 2014, 39). This interaction additionally has not taken into consideration the Indian Health System, or IHS, which “is a nationwide network of hospitals and clinics that services 1.9 million American Indians and Alaskan Natives who belong to some 564 tribes across 35 states with only $4.4 billion” (Kruse et al. 2016, 1). The IHS operates independently with limited resources, and the population served by this network have exacerbated rates of type 2 diabetes, cardiovascular disease, and the highest national rate of substance abuse (Kruse et al. 2016). Through use of IPUMS census data, I will integrate these considerations into my analysis of Indigenous access to healthcare.

# Data and Methods

The data used in this study was sourced from IPUMS USA, an organization that provides access to United States census data with enhanced documentation. The data was accessed on May 5th via data extract function on the organization's website. The sample includes 3,064 households and 6,405 indivuals from 2017 to 2018, and it is generalizable to the population of the United States. 

# Results

# Conclusions

# References
